const MEDECINES_DATA = [
  {
    _id: 1,
    name: "Ibuprofen",
    generic: "Paracetamol",
    type: "Tablet",
    price: 12,
    quantity: 23,
    addToCart: "add to cart",
    action: "action",
    shelf: "SH-34",
    rack: "2",
    barcode: "11111",
  },
  {
    _id: 2,
    name: "Letaminol",
    generic: "Nivaquin",
    type: "Syrup",
    price: 26,
    quantity: 164,
    addToCart: "add to cart",
    action: "action",
    shelf: "SH-34",
    rack: "8",
    barcode: "22222",
  },
  {
    _id: 3,
    name: "Aminatolicen",
    generic: "Amino-acid",
    type: "Tablet",
    price: 33,
    quantity: 5,
    addToCart: "add to cart",
    action: "action",
    shelf: "SH-6",
    rack: "19",
    barcode: "33333",
  },
  {
    _id: 4,
    name: "Letamil",
    generic: "Nivaquin",
    type: "Tablet",
    price: 12,
    quantity: 453,
    addToCart: "add to cart",
    action: "action",
    shelf: "SH-09",
    rack: "004",
    barcode: "44444",
  },
  {
    _id: 5,
    name: "Nivatol",
    generic: "Amino-acid",
    type: "Cream",
    price: 22,
    quantity: 153,
    addToCart: "add to cart",
    action: "action",
    shelf: "SH-112",
    rack: "24",
    barcode: "55555",
  },
  {
    _id: 6,
    name: "Ketazol",
    generic: "Amizol",
    type: "Cream",
    price: 45,
    quantity: 33,
    addToCart: "add to cart",
    action: "action",
    shelf: "SH-22",
    rack: "009",
    barcode: "66666",
  },
  {
    _id: 7,
    name: "Amino-vita",
    generic: "Amino-acid",
    type: "Syrup",
    price: 29,
    quantity: 93,
    addToCart: "add to cart",
    action: "action",
    shelf: "SH-99",
    rack: "290",
    barcode: "77777",
  },
  {
    _id: 8,
    name: "Ceramin",
    generic: "Amino-acid",
    type: "Tablet",
    price: 2,
    quantity: 153,
    addToCart: "add to cart",
    action: "action",
    shelf: "SH-008",
    rack: "89",
    barcode: "88888",
  },
  {
    _id: 9,
    name: "Glutamin",
    generic: "Glutamate",
    type: "Syrup",
    price: 45,
    quantity: 3,
    addToCart: "add to cart",
    action: "action",
    shelf: "SH-90",
    rack: "3",
  },
  {
    _id: 10,
    name: "Chloroquin",
    generic: "Chloro",
    type: "Tablet",
    price: 5,
    quantity: 342,
    addToCart: "add to cart",
    action: "action",
    shelf: "SH-321",
    rack: "560",
  },
  {
    _id: 11,
    name: "Efferalgan",
    generic: "Paracetamol",
    type: "Tablet",
    price: 7,
    quantity: 73,
    addToCart: "add to cart",
    action: "action",
    shelf: "SH-34",
    rack: "2",
  },
  {
    _id: 12,
    name: "Sedaspir",
    generic: "Paracetamol",
    type: "Tablet",
    price: 9,
    quantity: 13,
    addToCart: "add to cart",
    action: "action",
    shelf: "SH-34",
    rack: "209",
  },
  {
    _id: 13,
    name: "Alfmine",
    generic: "Vitamin",
    type: "Tablet",
    price: 21,
    quantity: 15,
    addToCart: "add to cart",
    action: "action",
    shelf: "SH-04",
    rack: "2",
  },
  {
    _id: 14,
    name: "Celafanin",
    generic: "Celafamin",
    type: "Tablet",
    price: 78,
    quantity: 143,
    addToCart: "add to cart",
    action: "action",
    shelf: "SH-39",
    rack: "20",
  },
  {
    _id: 15,
    name: "Nitazol",
    generic: "Amino-acid",
    type: "Cream",
    price: 29,
    quantity: 13,
    addToCart: "add to cart",
    action: "action",
    shelf: "SH-76",
    rack: "2",
  },
  {
    _id: 16,
    name: "Peniciline",
    generic: "Penilin",
    type: "Cream",
    price: 15,
    quantity: 5,
    addToCart: "add to cart",
    action: "action",
    shelf: "SH-34",
    rack: "29",
  },
  {
    _id: 17,
    name: "Nitronazol",
    generic: "Nitroo-acid",
    type: "Tablet",
    price: 9,
    quantity: 130,
    addToCart: "add to cart",
    action: "action",
    shelf: "SH-34",
    rack: "22",
  },
];

export default MEDECINES_DATA;
